### ISSUE TITLE
Error: no member named 'packet_info_idx' when compiling on OSX 10.6.8

### ISSUE THREAD

**Issue by ojfd** [EuFlo/sacd-ripper#2]
I get six errors and several tens (!) of "blocks" of warnings (see below) when trying to compile on Mac OSX 10.6.8. Compiling fails, obviously. Original sacd-ripper v.0.38 and v.0.39 by setmind (with little tweaks) compile fine under similar conditions.

/sacd-ripper-0.3.9.3/libs/libsacd/scarletbook_read.c:650:13: error: no member named 'packet_info_idx' in
      'scarletbook_handle_t'; did you mean 'frame_info_idx'?
    handle->packet_info_idx = 0;
            ^~~~~~~~~~~~~~~
            frame_info_idx
/sacd-ripper-0.3.9.3/tools/sacd_extract/../../libs/libsacd/scarletbook.h:606:32: note: 'frame_info_idx'
      declared here
    int                        frame_info_idx;  // added for retrieving timecode of current frame;   e.g. ...
                               ^
/sacd-ripper-0.3.9.3/libs/libsacd/scarletbook_read.c:706:21: error: no member named 'packet_info_idx' in
      'scarletbook_handle_t'; did you mean 'frame_info_idx'?
        if (handle->packet_info_idx == handle->audio_sector.header.packet_info_count) 
                    ^~~~~~~~~~~~~~~
                    frame_info_idx
/sacd-ripper-0.3.9.3/tools/sacd_extract/../../libs/libsacd/scarletbook.h:606:32: note: 'frame_info_idx'
      declared here
    int                        frame_info_idx;  // added for retrieving timecode of current frame;   e.g. ...
                               ^
/sacd-ripper-0.3.9.3/libs/libsacd/scarletbook_read.c:708:21: error: no member named 'packet_info_idx' in
      'scarletbook_handle_t'; did you mean 'frame_info_idx'?
            handle->packet_info_idx = 0;
                    ^~~~~~~~~~~~~~~
                    frame_info_idx
/sacd-ripper-0.3.9.3/tools/sacd_extract/../../libs/libsacd/scarletbook.h:606:32: note: 'frame_info_idx'
      declared here
    int                        frame_info_idx;  // added for retrieving timecode of current frame;   e.g. ...
                               ^
/sacd-ripper-0.3.9.3/libs/libsacd/scarletbook_read.c:756:24: error: no member named 'packet_info_idx' in
      'scarletbook_handle_t'; did you mean 'frame_info_idx'?
        while (handle->packet_info_idx < handle->audio_sector.header.packet_info_count && sector_bad_reads == 0)
                       ^~~~~~~~~~~~~~~
                       frame_info_idx
/sacd-ripper-0.3.9.3/tools/sacd_extract/../../libs/libsacd/scarletbook.h:606:32: note: 'frame_info_idx'
      declared here
    int                        frame_info_idx;  // added for retrieving timecode of current frame;   e.g. ...
                               ^
/sacd-ripper-0.3.9.3/libs/libsacd/scarletbook_read.c:758:80: error: no member named 'packet_info_idx' in
      'scarletbook_handle_t'; did you mean 'frame_info_idx'?
            audio_packet_info_t* packet = &handle->audio_sector.packet[handle->packet_info_idx];
                                                                               ^~~~~~~~~~~~~~~
                                                                               frame_info_idx
/sacd-ripper-0.3.9.3/tools/sacd_extract/../../libs/libsacd/scarletbook.h:606:32: note: 'frame_info_idx'
      declared here
    int                        frame_info_idx;  // added for retrieving timecode of current frame;   e.g. ...
                               ^
/sacd-ripper-0.3.9.3/libs/libsacd/scarletbook_read.c:825:21: error: no member named 'packet_info_idx' in
      'scarletbook_handle_t'; did you mean 'frame_info_idx'?
            handle->packet_info_idx++;
                    ^~~~~~~~~~~~~~~
                    frame_info_idx
/sacd-ripper-0.3.9.3/tools/sacd_extract/../../libs/libsacd/scarletbook.h:606:32: note: 'frame_info_idx'
      declared here
    int                        frame_info_idx;  // added for retrieving timecode of current frame;   e.g. ...
                               ^
6 errors generated.

====================

Warnings, generated by:

1. Clang

clang: warning: -lxml2: 'linker' input unused when '-c' is present
clang: warning: -lz: 'linker' input unused when '-c' is present
clang: warning: -lpthread: 'linker' input unused when '-c' is present
clang: warning: -licucore: 'linker' input unused when '-c' is present
clang: warning: -lm: 'linker' input unused when '-c' is present

2. GCC

i686-apple-darwin11-llvm-gcc-4.2: -lxml2: linker input file unused because linking not done
i686-apple-darwin11-llvm-gcc-4.2: -lz: linker input file unused because linking not done
i686-apple-darwin11-llvm-gcc-4.2: -lpthread: linker input file unused because linking not done
i686-apple-darwin11-llvm-gcc-4.2: -licucore: linker input file unused because linking not done
i686-apple-darwin11-llvm-gcc-4.2: -lm: linker input file unused because linking not done

**Comment by EuFlo** [comment]
I think you use an old file **scarletbook_read.c** (older than 4 months).
The var **packet_info_idx**  is no longer used at line 650.
Please make git pull.
And then try to compile.

**Comment by ojfd** [comment]
Thanks EuFlo!
The files were indeed from Feb 2020. I downloaded your latest master (git is problematic on 10.6.8) and it does compile, but all other warnings remain.
[Mac_SL_build_errors.txt.zip](https://github.com/EuFlo/sacd-ripper/files/4832596/Mac_SL_build_errors.txt.zip)

**Comment by EuFlo** [comment]
All warnings are the 'normal' ones. 
All messages are not important and are inherited from the master fork.
